# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a2b6eb2f6989ef8e031c43a61b1e327f8a9289adb8e24c2dc2390c8a8e926fe1e11fceb77d68750683cc5a9cd97ca38d30e1a19cddad1ae729d87d3f7967e33

test:
  secret_key_base: fb5c679af3ca76de96b4df7269339eaa254c481f9b328501d761b3c564f13f360cd67cca0b0ec08df0889d02c0bab9218262b9c1b4341caac84a9b01b4d45445

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
